services:
  password-keeper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: password-keeper
    working_dir: /app
    volumes:
      - ./:/app
      - target_cache:/app/target
      - cargo_registry:/usr/local/cargo/registry
    #command: cargo watch -x run
    command: tail -f /dev/null
    networks:
      - password_keeper_network

networks:
  password_keeper_network:
    driver: bridge

volumes:
  target_cache:
  cargo_registry:

name: password_keeper
